# Generated by Django 5.2.8 on 2025-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_discount_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
    ]
