# Generated by Django 5.2.8 on 2025-11-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_options_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmoduleprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='studentmoduleprogress',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Digital Marketing', 'Expert Digital Marketing'), ('Web Development', 'Web Development'), ('Canva', 'Canva')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SModule',
        ),
        migrations.DeleteModel(
            name='StudentModuleProgress',
        ),
    ]
