# Generated by Django 5.2.8 on 2025-12-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_studentmoduleprogress_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scourse',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.scourse'),
        ),
    ]
