# Generated by Django 5.2.8 on 2025-12-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_scourse_name_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scourse',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Digital Marketing', 'Expert Digital Marketing'), ('Web Development', 'Web Development'), ('Canva', 'Canva')], max_length=50),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='modules/')),
                ('completion', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.scourse')),
            ],
        ),
    ]
