# Generated by Django 5.2.8 on 2025-12-01 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_scourse_name_alter_student_course_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='completion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
