# Generated by Django 5.2.8 on 2025-12-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_module_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scourse',
            options={'ordering': ['name']},
        ),
    ]
