# Generated by Django 5.2.8 on 2025-12-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_scourse_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smaterial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.scourse'),
        ),
    ]
