# Generated by Django 5.2.8 on 2025-12-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_tasksubmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='drive_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TaskSubmissions',
        ),
    ]
