# Generated by Django 5.2.8 on 2025-12-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tasksubmission_drive_file_url_delete_tasksubmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
