# Generated by Django 5.2.8 on 2025-12-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tasksubmission_original_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='drive_file_url',
            new_name='drive_link',
        ),
    ]
