# Generated by Django 5.2.8 on 2025-12-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_drive_file_url_tasksubmission_drive_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='drive_link',
            new_name='drive_file_url',
        ),
    ]
