# Generated by Django 5.2.8 on 2025-12-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('Digital Marketing', 'Expert Digital Marketing'), ('Web Development', 'Web Development'), ('Canva', 'Canva')], max_length=50, null=True),
        ),
    ]
