# Generated by Django 5.2.8 on 2025-12-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_course_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smaterial',
            options={'verbose_name': 'Materilas', 'verbose_name_plural': 'Materials'},
        ),
    ]
