# Generated by Django 5.2.8 on 2025-12-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_smaterial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='company_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course_duration',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course_timing',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening'), ('weekend', 'Weekend')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='end_goal',
            field=models.CharField(blank=True, choices=[('job', 'Get Job'), ('business', 'Start Business'), ('skill', 'Learn New Skills')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, choices=[('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('delhi', 'Delhi')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('working', 'Working Professional'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='smaterial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
