# Generated by Django 5.2.8 on 2025-12-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_student_company_college_student_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_duration',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('2_months', '2 Months'), ('1_week', '1 week')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_timing',
            field=models.CharField(blank=True, choices=[('11_14', '11:00AM - 2:00PM'), ('15_18', '3:00PM - 6:00PM '), ('18_21', '6:00PM - 9:00PM'), ('18.5_21.5', '2:30PM - 9:30PM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_goal',
            field=models.CharField(blank=True, choices=[('To became a freelancer', 'To became a freelancer'), ('To Study Marketing for own business', 'To Study Marketing for own business'), ('For job', 'For job'), ('For career growth', 'For career growth')], max_length=50, null=True),
        ),
    ]
