# Generated by Django 5.2.8 on 2025-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_student_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
