# Generated by Django 5.2.8 on 2025-12-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_student_location_alter_student_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_duration',
            field=models.CharField(blank=True, choices=[('2 - Months', '2 - Months'), ('1 - Month', '1 - Month'), ('1 - Week', '1 - Week')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_timing',
            field=models.CharField(blank=True, choices=[('11:00 AM - 2:00 PM', '11:00 AM - 2:00 PM'), ('3:00 PM - 6:00 PM', '3:00 PM - 6:00 PM '), ('6:00 PM - 9:00 PM', '6:00 PM - 9:00 PM'), ('6:30 PM - 9:30 PM', '6:30 PM - 9:30 PM')], max_length=50, null=True),
        ),
    ]
