# Generated by Django 5.2.8 on 2025-12-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
