# Generated by Django 5.2.8 on 2025-12-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
