# Generated by Django 5.2.8 on 2025-12-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_student_profile_image_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='student_profiles/default.png', null=True, upload_to='student_profiles/'),
        ),
    ]
