# Generated by Django 5.2.8 on 2025-12-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_attendanceperiod_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('period', 'date')},
        ),
    ]
