# Generated by Django 5.2.8 on 2025-12-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceperiod',
            name='student',
        ),
        migrations.AddField(
            model_name='attendanceperiod',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='attendance_periods', to='main.student'),
        ),
    ]
