# Generated by Django 5.2.8 on 2025-12-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_attendanceperiod_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'Attendance Period', 'verbose_name_plural': 'Attendance & Periods'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ManyToManyField(related_name='attendances', to='main.student'),
        ),
    ]
