# Generated by Django 5.2.8 on 2025-12-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_attendance_student_attendance_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'period')},
        ),
    ]
